name: Static Site Build Deployment Workflow

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      HOSTED_ZONE_NAME:
        required: true
      HOSTED_ZONE_ID:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout React repo
        uses: actions/checkout@v4

      - name: Checkout Infra repo
        uses: actions/checkout@v4
        with:
          repository: jothamteshome/reusable-github-actions-workflows
          path: infra

      - name: Format repository name correctly
        run: |
          FULL_REPO_NAME="${{ github.repository }}"
          FORMATTED_REPO_NAME=${FULL_REPO_NAME##*/}
          echo "FORMATTED_REPO_NAME=$FORMATTED_REPO_NAME" >> $GITHUB_ENV
          echo "FORMATTED_REPO_NAME=$FORMATTED_REPO_NAME"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Node & Build React
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm run build

      - name: Install CDK CLI
        run: |
          npm install -g aws-cdk

      - name: Install CDK requirements
        working-directory: infra/deploy-static-site
        run: pip install -r requirements.txt

      - name: Deploy CDK stack
        working-directory: infra/deploy-static-site
        env:
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: cdk deploy --app "python3 app.py" --context repo_name="$FORMATTED_REPO_NAME" --require-approval never
      
      - name: Get Bucket Name & CloudFront ID
        id: get_outputs
        run: |
          STACK_NAME="${FORMATTED_REPO_NAME}-static-site"
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='BucketNameOutput'].OutputValue" \
            --output text)
          CLOUDFRONT_ID=$(aws cloudformation describe-stacks \
            --stack-name $STACK_NAME \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontIdOutput'].OutputValue" \
            --output text)
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> $GITHUB_ENV

      - name: Sync React build to S3
        run: |
          if [ -d "build/client" ]; then
            BUILD_DIR="build/client/"
          elif [ -d "build" ]; then
            BUILD_DIR="build/"
          elif [ -d "dist" ]; then
            BUILD_DIR="dist/"
          elif [ -d ".next" ]; then
            BUILD_DIR=".next/"
          else
            echo "No known build directory found!"
            exit 1
          fi

          echo "Using build directory: $BUILD_DIR"
          aws s3 sync $BUILD_DIR s3://$BUCKET_NAME --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

