name: Update Latest Tag for Deploy Workflow

on:
  push:
    tags:
      - 'deploy-static-site-v*'

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update deploy-static-site-latest tag
        run: |
          echo "Updating 'deploy-static-site-latest' tag to $GITHUB_SHA"
          # Delete local deploy-static-site-latest tag if it exists
          git tag -f deploy-static-site-latest
          
          # Point deploy-static-site-latest tag to current commit
          git tag -f deploy-static-site-latest $GITHUB_SHA
          
          # Push updated deploy-static-site-latest tag to origin
          git push origin -f deploy-static-site-latest